name: ecomerce_app_two
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  badges: ^3.1.2
  bounce: ^1.0.2
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icon/image.png"
  adaptive_icon_foreground: "assets/icon/image.png"
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
    - assets/
